--- 
- name: dat ip cho loobpack
  hosts: all
  gather_facts: no
  tasks:
    - name: Set loopback IPv4 address # Ð?t tên task d? qu?n lý
      ios_l3_interface: # do c?u hình router nên b?t bu?c khai báo nhu v?y
        name_id: "{{item.number}}" # tên c?ng
        ipv4: "{{item.ipv4}}" # d?a ch? IP c?a loopback
        state: present
      with_items:
        - { number: 1, ipv4: "10.0.1.1/24" }
        - { number: 2, ipv4: "10.0.2.1/24" }
        - { number: 3, ipv4: "10.0.3.1/24" }
        
    - name: Show ip
      ios_command: # Viết lệnh để gửi ở mode command line của router
        commands:
          - show ip int brief
      register: show_ip # gắn kết quả vào biến show_ip
